CREATE TABLE password_resets(
  id BIGINT(21) UNSIGNED NOT NULL AUTO_INCREMENT,
  token VARCHAR(32) NOT NULL,
  user_id BIGINT(21) UNSIGNED,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY(id)
);

ALTER TABLE password_resets ADD INDEX(token);