ALTER TABLE airlines DROP PRIMARY KEY;
ALTER TABLE airlines ADD COLUMN id BIGINT(21) UNSIGNED PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE airports DROP PRIMARY KEY;
ALTER TABLE airports ADD COLUMN id BIGINT(21) UNSIGNED PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE equipment ADD COLUMN id BIGINT(21) UNSIGNED PRIMARY KEY AUTO_INCREMENT FIRST;